### ISSUE TITLE
Group handling

### ISSUE THREAD

**Issue by red-h** [AlCalzone/ioBroker.tradfri#114]
First of all many thanks for the great work! The Tradfri adapter is one of the main parts in my HA.

I have a problem using groups when parts of them are not active. For example, if a bulb is not connected to the power, the status of the group resets. So if the group is turned on (state=true) - which was turned off before - the group will be reset to state=false.

If devices from a group are addressed directly, this behavior does not occur. The whole thing can be fixed with the virtual groups. Here the behavior is as I expect it to be.

But unfortunately I have another problem with virtual groups:
I recently bought the new outlets, which unfortunately do not appear in the device selection for virtual groups.

Is it possible to list the outlets in the device selection for virtual groups?

**Comment by red-h** [comment]
@AlCalzone can you please add support for the ikea outlets in the virtual groups? Currently I'm only able to add bulbs and drivers to a group.

**Comment by AlCalzone** [comment]
Hey @red-h, sorry for taking so long. The problem with groups is that the gateway does not inform us about changes. We have a bit more control over virtual groups. 

The additional device types (plugs and blinds) will be available in v2.5.0 (should be on npm in a few minutes). Let me know if that works for you (I don't have anything but bulbs to test).

**Comment by red-h** [comment]
Thanks for the answer. Unfortunately I can only test the plugs, because I don't have any blinds either. But I will test the plugs in the virtual groups during the public holidays and I will give you feedback at least for these.

So, Thanks for that in advanced and wish you Merry Christmas
Red

**Comment by AlCalzone** [comment]
Merry Christmas to you too!

**Comment by red-h** [comment]
I was able to test the new version shortly today. The plugs are now listed in the virtual groups. However, when the virtual group is triggered, the plugs are not acting. The other bulbs in the group behave normally.
Not sure if I can help you with logs etc. since there is nothing listed in the ioBrokers log tab.
Please let me know if I can assist with further tests or data.

**Comment by AlCalzone** [comment]
Thanks for the test, I forgot some places where I needed to add plug support. Please try v2.5.1 (available in a couple of minutes).

**Comment by zaunermax** [comment]
I have some blinds, if you need some testing done I can be of service

**Comment by zaunermax** [comment]
What I found out right away is, that setting blinds in the Group does in fact work but the Percentage values are wrong. 0% closes the blinds and 100% opens them which should be exactly the other way round.

This is also true when directly changing the values in the blind objects. I can create a new issue if you want.

**Comment by red-h** [comment]
Hi all, In the meantime I had time to test the new version. The plugs are now working perfectly in virtual groups. Thanks a lot!

**Comment by AlCalzone** [comment]
> 0% closes the blinds and 100% opens them which should be exactly the other way round.
> 
> This is also true when directly changing the values in the blind objects. I can create a new issue if you want.

That is on purpose. It is opposite to how it is in the IKEA app, but this way it aligns with other smart home technologies. For example, Alexa doesn't support blinds, so they are usually implemented as lights (where 0% is dark and 100% is full brightness).

**Comment by AlCalzone** [comment]
Anyways, thanks for the testing guys!
