### ISSUE TITLE
Creating groups in the app don't create objects until restart

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/ioBroker.tradfri#21]

**Comment by DutchmanNL** [comment]
not confirmed in 0.3.3 and 0.4.1, new group is immediatly visible in iobroker.

same counts for group removal, change is instantly synronised to iobroker

**Comment by AlCalzone** [comment]
That actually happened to me. Maybe something was iffy at the moment, haven't come around to testing it since then. I'll just leave it here until I can confirm the problem or not.

**Comment by AlCalzone** [comment]
Can't reproduce anymore, closing...
