### ISSUE TITLE
Tradfi Motion Sensor - new model

### ISSUE THREAD

**Issue by DoraDeu** [AlCalzone/ioBroker.tradfri#232]
I installed the new version of the motion sensor and it is successfully paired with a Paul Neuhaus Q-Panel. I can see them in one room of the IKEA app.
There is also a Tradfi Remote Control (5 button) connected to the LED Panel.
When the motion sensor is triggered it successfully switches the LED Panel on (and off after 3 minutes inactivity).
But when it switches the LED Panel on the status of the Panel in the adapter (and IKEA app) does not change (stays "off").
As I don´t have the older version of the motion sensor: Is this the normal behavior or does it normally work that the status of the light is updated when it is switched by the motion sensor?

When I switch the LED panel directly in the IKEA app, the status changes properly.

**Comment by AlCalzone** [comment]
I don't have any experience with the motion sensor, but...

I have a suspicion that the motion sensor communicates directly with the panel, so the gateway which provides the information does not know the panel was switched. The app and adapter both use the gateway to know the current state of the devices.

**Comment by DutchmanNL** [comment]
I think the question must be raised to IKEA for me it's normal that if the app does not see it the adaptor will also not see it.

If it's correct behaviour, IKEA should know?

**Comment by DoraDeu** [comment]
Sure, it could be the case that they communicate directly with each other but at least I would expect that the LED panel reports the changed status immediately to the gateway.
It would help to know if the old motion sensor works the same way.

**Comment by DutchmanNL** [comment]
> but at least I would expect that the LED panel reports the changed status immediately to the gateway.

Me too but as you state it's not the case, but again this is nothing we can solve but IKEA has to do

**Comment by AlCalzone** [comment]
> Is it normal that the motion sensor has just this DPs in the adapter?

Yes, that's all the gateway gives us to work with :(

**Comment by AlCalzone** [comment]
I'm going to close this since there's nothing I can do. Feel free to reopen when the gateway decides to send changes.
