### ISSUE TITLE
IKEA FYRTUR and KADRILJ

### ISSUE THREAD

**Issue by Moormerlander** [AlCalzone/ioBroker.tradfri#277]
Not really an issue, but an important question:
Does the adapter already support  IKEA FYRTUR and KADRILJ?
They are available now and I want to buy them, but only if I can use them in ioBroker.

**Comment by AlCalzone** [comment]
Yes, but you need the adapter version 2.4.4, which is only in the latest repo, not stable.

**Comment by Moormerlander** [comment]
perfect. just installed the latest vrion. good job!
