### ISSUE TITLE
RC recognized but no state changes

### ISSUE THREAD

**Issue by Moormerlander** [AlCalzone/ioBroker.tradfri#278]
I linked the Tradfri remote and can see all state objects, but when pressing any key on the remote nothing changes.

<img width="1175" alt="Bildschirmfoto 2019-10-18 um 20 13 23" src="https://user-images.githubusercontent.com/27990424/67117776-ce265680-f1e3-11e9-8e73-56537e7593d1.png">

**Comment by AlCalzone** [comment]
Sadly the Gateway does not send any information about remotes but the battery status.

**Comment by Moormerlander** [comment]
I bought the Gateway and the remote. So it's completely useless?

**Comment by AlCalzone** [comment]
Without any lights, yes. You can use the zigbee adapter to receive the remote's data, but you don't need the gateway for that.

**Comment by Moormerlander** [comment]
Thank you again. Just ordered one and I'm very curious if it works better than the Tradfri gateway.
