### ISSUE TITLE
Latest Version not running

### ISSUE THREAD

**Issue by Vrumfondel** [AlCalzone/iobroker.tradfri#3]
Environment: RasPI 2, latest ioBroker, node.js 7.10

All I get once the instance is created and configured:

`host.csprint01	2017-05-27 14:27:24.393	error	instance system.adapter.tradfri.0 terminated with code 1 ()
host.csprint01	2017-05-27 14:27:22.907	info	instance system.adapter.tradfri.0 started with pid 9746
host.csprint01	2017-05-27 14:27:21.566	info	Restart adapter system.adapter.tradfri.0 because enabled`

In additional Info is needed please let me know.

**Comment by AlCalzone** [comment]
Thanks for the report. The issue is known. One of the 3rd party libs seems to need additional setup/configuration/whatever, idk. I had it work on a raspi 2 but I can reproduce the issues.

I'm going to implement COAP and DTLS myself but that will take some time, since I'm currently moving.

**Comment by AlCalzone** [comment]
The problematic 3rd party libs have been rewritten and the adapter is ready to use again.
