### ISSUE TITLE
Problem with group

### ISSUE THREAD

**Issue by gaudes** [AlCalzone/ioBroker.tradfri#304]
Hi AlCalzone,

I have paired a Philips bulb with Tradfri. Since a few weeks, I have problems with this bulb.

I have a group called "Sofalampe" in Tradfri, it contains only the Philips bulb.

When switching the bulb off through the group, the state changes and switches back after a short time to true, but the bulb is off. So it's impossible to switch it on again.

Solution is switching off in the Tradfri off and on again, then the bulb is on again.

But when I switch off the bulb directly on the bulb object in ioBroker, not via the group, it works.

Here a log from switching directly off through the bulb:

tradfri.0 | 2019-11-12 19:24:53.230 | debug | {{blue}} state with id tradfri.0.G-131075.state updated: ack=true; val=false
-- | -- | -- | --
tradfri.0 | 2019-11-12 19:24:53.225 | debug | {{blue}} state with id tradfri.0.G-131075.brightness updated: ack=true; val=100
tradfri.0 | 2019-11-12 19:24:52.972 | debug | {{blue}} state with id tradfri.0.L-65569.batteryPercentage updated: ack=true; val=null
tradfri.0 | 2019-11-12 19:24:52.972 | debug | {{blue}} state with id tradfri.0.L-65569.lightbulb.state updated: ack=true; val=false
tradfri.0 | 2019-11-12 19:24:52.972 | debug | {{blue}} state with id tradfri.0.L-65569.lightbulb.brightness updated: ack=true; val=100
tradfri.0 | 2019-11-12 19:24:52.968 | debug | {{blue}} state with id tradfri.0.L-65569.lightbulb.transitionDuration updated: ack=true; val=1
tradfri.0 | 2019-11-12 19:24:52.966 | debug | {{blue}} state with id tradfri.0.L-65569.lastSeen updated: ack=true; val=1573581789
tradfri.0 | 2019-11-12 19:24:52.964 | debug | {{blue}} state with id tradfri.0.L-65569.alive updated: ack=true; val=true
tradfri.0 | 2019-11-12 19:24:52.963 | debug | observeDevice > {"3":{"0":"Philips","1":"LWB010","2":"","3":"1.23.0_r20156","6":1},"3311":[{"5850":0,"5851":254,"9003":0}],"5750":2,"9001":"Sofalampe","9002":1573581782,"9003":65569,"9019":1,"9020":15
tradfri.0 | 2019-11-12 19:24:52.669 | debug | updateResource(15001/65569) > sending payload: {"3311":[{"5712":5,"5850":0}]}
tradfri.0 | 2019-11-12 19:24:52.669 | debug | updateResource(15001/65569) > comparing {"isProxy":true,"options":{},"name":"Sofalampe","createdAt":1573581782,"instanceId":65569,"type":2,"alive":true,"lastSeen":1573581789,"otaUpdateState":0,"device
tradfri.0 | 2019-11-12 19:24:52.668 | debug | {{blue}} state with id tradfri.0.L-65569.lightbulb.state updated: ack=false; val=false

The bulb is now switched off and the state in ioBroker and the Tradfri app is correct.

Now the same switching off action using the group in ioBroker:

tradfri.0 | 2019-11-12 19:26:58.261 | debug | {{blue}} state with id tradfri.0.G-131075.brightness updated: ack=true; val=100
-- | -- | -- | --
tradfri.0 | 2019-11-12 19:26:58.259 | debug | {{blue}} state with id tradfri.0.G-131075.state updated: ack=true; val=true
tradfri.0 | 2019-11-12 19:26:58.026 | debug | {{blue}} state with id tradfri.0.G-131075.saturation updated: ack=true; val=null
tradfri.0 | 2019-11-12 19:26:58.025 | debug | {{blue}} state with id tradfri.0.G-131075.hue updated: ack=true; val=null
tradfri.0 | 2019-11-12 19:26:58.025 | debug | {{blue}} state with id tradfri.0.G-131075.color updated: ack=true; val=null
tradfri.0 | 2019-11-12 19:26:58.025 | debug | {{blue}} state with id tradfri.0.G-131075.colorTemperature updated: ack=true; val=null
tradfri.0 | 2019-11-12 19:26:58.025 | debug | {{blue}} state with id tradfri.0.G-131075.brightness updated: ack=true; val=0
tradfri.0 | 2019-11-12 19:26:58.025 | debug | {{blue}} state with id tradfri.0.G-131075.transitionDuration updated: ack=true; val=null
tradfri.0 | 2019-11-12 19:26:58.014 | debug | {{blue}} state with id tradfri.0.G-131075.state updated: ack=true; val=false
tradfri.0 | 2019-11-12 19:26:58.009 | debug | {{blue}} state with id tradfri.0.G-131075.activeScene updated: ack=true; val=196616
tradfri.0 | 2019-11-12 19:26:57.807 | debug | updateResource(15004/131075) > sending payload: {"5850":0}
tradfri.0 | 2019-11-12 19:26:57.807 | debug | updateResource(15004/131075) > comparing {"isProxy":true,"options":{},"name":"Sofalampe","createdAt":1515100196,"instanceId":131075,"onOff":false,"dimmer":100,"deviceIDs":[65569],"sceneId":196616,"gro
tradfri.0 | 2019-11-12 19:26:57.806 | debug | {{blue}} state with id tradfri.0.G-131075.state updated: ack=false; val=false

Result is: Bulb is off, ioBroker state for the group and the bulb is on, Tradfri app also shows it as on.

I've reconnected the bulb to Tradfri already.

Any ideas ? 

Thanks and regards,

Ralf

**Comment by gaudes** [comment]
Hello again,

I found one more thing:

The only values filled are brightness and state:

![image](https://user-images.githubusercontent.com/34286177/68991380-86d0cb80-085e-11ea-9392-3922388df0e2.png)

Before I could set the color of the bulb. But it still works with the native Tradfri app on my iPhone.

Thanks and regards,

Ralf

**Comment by AlCalzone** [comment]
Hey, does this still happen? It seems like the gateway doesn't notify the app and ioBroker that the bulb is off when you switch it through the group. Not much I can do there.

Regarding your 2nd comment: You should still be able to edit the values, even if they are not displayed.

**Comment by gaudes** [comment]
Hey AlCalzone,

I've made a workaround: I used the bulb directly, not the group.

Maybe it's a bug from IKEA or an incompatibility with the bulb.

After switching directly the bulb, which is a single bulb in a lamp, everything works like before.

I'd close this case, due to my workaround.

Thanks and regards, Ralf
