### ISSUE TITLE
New Tradfri Device - Symfonisk

### ISSUE THREAD

**Issue by fischl3r** [AlCalzone/ioBroker.tradfri#352]
Link to the Device: https://www.ikea.com/de/de/p/symfonisk-fernbedienung-fuer-soundsystem-weiss-60370480/

click 
double click
triple Click 
and a analog value 

tradfri.0 | 2020-01-04 22:27:41.735 | warn | (26787) Unknown accessory type 8. Please send this info to the developer with a short description of the device!
-- | -- | -- | --
tradfri.0 | 2020-01-04 22:27:41.729 | warn | (26787) object was: {"3":{"0":"IKEA of Sweden","1":"SYMFONISK Sound Controller","2":"","3":"2.1.022","6":3,"9":21},"5750":8,"9001":"Test","9002":1578171261,"9003":65540,"9019":1,"9020":1578171395,"90
tradfri.0 | 2020-01-04 22:27:41.729 | warn | (26787) found unknown property with key 15018

**Comment by AlCalzone** [comment]
Sadly this doesn't include any information about the pressed buttons - just like the normal remotes.

**Comment by Baenker** [comment]
for the symfonisk the sonos Adapter should work.

**Comment by AlCalzone** [comment]
The warning is suppressed in v2.5.2
