### ISSUE TITLE
Adapter won´t start

### ISSUE THREAD

**Issue by bytec77** [AlCalzone/ioBroker.tradfri#38]
I got this message in the log.

`

host.iobroker | 2018-02-03 16:32:53.096 | error | instance system.adapter.tradfri.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2018-02-03 16:32:53.096 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at Module._compile (module.js:570:32)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.tradfri/node_modules/node-tradfri-client/node_modules/node-coap-client/node_modules/node-dtls-client/node_modules/node
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at Module.require (module.js:497:17)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at Function.Module._load (module.js:417:25)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: at Function.Module._resolveFilename (module.js:469:15)
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.tradfri/node_modules/node-tradfri-client/node_modules/node-coap-client/node_modules/node-dtls-client/node_modules/node
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: ^
Caught | 2018-02-03 16:32:53.095 | error | by controller[0]: throw err;
Caught | 2018-02-03 16:32:53.094 | error | by controller[0]: module.js:471

`

**Comment by AlCalzone** [comment]
The Logs indicate that one dependency wasn‘t installed. Can you reinstall the adapter and post Logs of the installation so we can find out why?

**Comment by bytec77** [comment]
Here the log.

`root@iobroker:/opt/iobroker# npm install iobroker.tradfri --production --prefix "/opt/iobroker"

authenticate-pam@1.0.2 install /opt/iobroker/node_modules/authenticate-pam
node-gyp rebuild

make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird betreten
  CXX(target) Release/obj.target/authenticate_pam/authenticate_pam.o
../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden
 #include <security/pam_appl.h>
                               ^
compilation terminated.
authenticate_pam.target.mk:94: die Regel für Ziel „Release/obj.target/authenticate_pam/authenticate_pam.o“ scheiterte
make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.0-3-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
iobroker@1.0.0 /opt/iobroker
└── iobroker.tradfri@1.0.6 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
root@iobroker:/opt/iobroker# 
`

**Comment by AlCalzone** [comment]
Hmm... that's none of tradfri's dependencies... Can you try the following please:
```
iobroker del tradfri
cd /opt/iobroker/node_modules
sudo rm -rf node-coap-client
sudo rm -rf node-dtls-client
sudo rm -rf node-aead-crypto
```
before reinstalling the adapter? The `rm` commands might throw an error because something wasn't found - that's ok.

**Comment by bytec77** [comment]
Thanx. 

After I do the rm´s an reinstall the Adapter it works.
