### ISSUE TITLE
SIGABRT when starting adapter

### ISSUE THREAD

**Issue by bonan** [AlCalzone/iobroker.tradfri#4]
Adapter dies directly with SIGABRT:
```
host.iot	2017-05-28 17:38:22.297	error	instance system.adapter.tradfri.0 terminated with code null ()
host.iot	2017-05-28 17:38:22.297	warn	instance system.adapter.tradfri.0 terminated due to SIGABRT
host.iot	2017-05-28 17:38:21.660	info	instance system.adapter.tradfri.0 started with pid 11695
```

Running main.js manually (obfuscated host and psk):
```
These are our DTLS client opts:   {"host":"172.x.y.z","port":5684,"psk":{"type":"Buffer","data":[]},"PSKIdent":{"type":"Buffer","data":[65,65,65,65,65,65,65,65,65,65,65,65,
65,65,65]},"key":null,"peerPublicKey":null}
send_safety_check()

step() beginning
step() beginning
io.tradfri.0: ../../nan/nan.h:695: Nan::MaybeLocal<v8::Object> Nan::CopyBuffer(const char*, uint32_t): Assertion `size <= imp::kMaxLength && "too large buffer"' failed.
Aborted
```

Same result both on raspberry pi 3 (ARM) and an amd64 virtual machine

**Comment by AlCalzone** [comment]
Thanks for the report. The issue is known. One of the 3rd party libs seems to need additional setup/configuration/whatever, idk. I had it work on a raspi 2 but I can reproduce the above errors.

I'm going to implement COAP and DTLS myself but that will take some time, since I'm currently moving.

**Comment by AlCalzone** [comment]
The problematic 3rd party libs have been rewritten and the adapter is ready to use again.
