### ISSUE TITLE
query members of virtual groups

### ISSUE THREAD

**Issue by NemoN** [AlCalzone/ioBroker.tradfri#40]
It is possible to get the members of (virtual) groups?

for example:

`var array = apdapter.getMembers('<groupID>');`

**Comment by AlCalzone** [comment]
You can. The virtual group object looks like this:
```js
{
  "_id": "tradfri.0.VG-00001",
  "type": "channel",
  "common": {
    "name": "Test"
  },
  "native": {
    "instanceId": 1,
    "type": "virtual group",
    "deviceIDs": [
      65537,
      65538
    ]
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "enums": {},
  "from": "system.adapter.tradfri.0",
  "ts": 1515160645444
}
```
So once you read the object with getObject, `obj.native.deviceIDs` contains the instance ids of the members. Those are always lightbulbs, so their IDs have the form `"tradfri.X.L-YYYYY"`

**Comment by NemoN** [comment]
Some background of my question: I have a virtual group with 10 GU-10 bulbs. Sometimes 1-3 bulbs of the group don't react. If i retrigger the switch on/off command it works. My plan was now:

For example turning off all lamps:

- Turn off virtual group
- Check each lamp in group for state still on
- Turn this lamp(s) off again

This works now. Maybe this could be handled from backend/Tradfri adapter too?

**Comment by AlCalzone** [comment]
> This works now. Maybe this could be handled from backend/Tradfri adapter too?

Sounds reasonable, I'll need some additional input though. When that happens:
* Do the lamps which did not react update their state in ioBroker? I imagine they don't.
* Do the virtual group's states get updated?

**Comment by NemoN** [comment]
> Do the lamps which did not react update their state in ioBroker? I imagine they don't.

No the status is still `tradfri.0.L-65549.lightbulb.state = 'true' `
(if i trigger a "off" command)

> Do the virtual group's states get updated?

If some bulbs of the VG can't switched, then the VG group state is empty `tradfri.0.VG-00001.state = ''`

my working workaround is now after turning off the VG group before

```
var newState = true;
var obj = getObject('tradfri.0.VG-00001');
var members = obj.native.deviceIDs;

members.forEach(function(m) {
    var stateId = 'tradfri.0.L-' + m + '.lightbulb.state';
    // console.log(stateId);

    getState(stateId, function (error, state) {
        // console.log(state.val);
        if (error) {
           console.log(error);
        } else {
            if (state.val != newState) { // Lampe hat den falschen State, nochmal schalten!
                setState(stateId, newState, false, function() { 
                    if (newState) {
                        log(stateId + ' turned ON again!');
                    } else {
                        log(stateId + ' turned OFF again!');
                    }
                });
            }
        }
    });
});
```

**Comment by AlCalzone** [comment]
Ok thanks. One more thing:
Does the log show any errors when this happens? Something along the lines of `unhandled promise rejection`?

**Comment by NemoN** [comment]
no errors
