### ISSUE TITLE
Status eines Schalters auslesen möglich?

### ISSUE THREAD

**Issue by Neverseen0815** [AlCalzone/ioBroker.tradfri#446]
Hallo,

gibt es eine Möglichkeit den Status eines Schalters auszulesen?
Erkannt wird er ja korrekt aber leider sieht man nur den Zustand der Batterie, den Zeitstempel der letzten Aktion, Name und den "Alive" Status.

**Comment by AlCalzone** [comment]
Leider nein. Der Adapter kann nur anzeigen, was das Gateway an Infos bereit stellt. Der Schalterstatus gehört leider nicht dazu.
