### ISSUE TITLE
tradfri adapter won't start

### ISSUE THREAD

**Issue by axelrathey** [AlCalzone/ioBroker.tradfri#46]
Hi,

the tradfri adapter does not start on my banana pi. Below there ist an error list I see after starting the tradfri adapter.
I'm not sure, if all the errors are part of the tradfri adapter.

Thank you for any help

Axel

host.bananapi | 2018-04-16 20:15:36.754 | error | instance system.adapter.tradfri.0 terminated with code 1 ()
-- | -- | -- | --
host.bananapi | 2018-04-16 20:15:36.754 | error | Caught by controller[0]:     at startListening (dgram.js:121:10)
host.bananapi | 2018-04-16 20:15:36.754 | error | Caught by controller[0]:     at Socket.emit (events.js:185:7)
host.bananapi | 2018-04-16 20:15:36.753 | error | Caught by controller[0]:     at emitNone (events.js:86:13)
host.bananapi | 2018-04-16 20:15:36.753 | error | Caught by controller[0]:     at Socket.udp_onListening (/opt/iobroker/node_modules/node-dtls-client/build/dtls.js:111:37)
host.bananapi | 2018-04-16 20:15:36.752 | error | Caught  by controller[0]:     at new ClientHandshakeHandler  (/opt/iobroker/node_modules/node-dtls-client/build/DTLS/HandshakeHandler.js:125:14)
host.bananapi | 2018-04-16 20:15:36.752 | error | Caught  by controller[0]:     at ClientHandshakeHandler.renegotiate  (/opt/iobroker/node_modules/node-dtls-client/build/DTLS/HandshakeHandler.js:176:14)
host.bananapi | 2018-04-16 20:15:36.752 | error | Caught  by controller[0]:     at ClientHandshakeHandler.sendFlight  (/opt/iobroker/node_modules/node-dtls-client/build/DTLS/HandshakeHandler.js:342:14)
host.bananapi | 2018-04-16 20:15:36.751 | error | Caught  by controller[0]:     at ClientHandshakeHandler.sendFlight_finish  (/opt/iobroker/node_modules/node-dtls-client/build/DTLS/HandshakeHandler.js:326:26)
host.bananapi | 2018-04-16 20:15:36.751 | error | Caught  by controller[0]:     at RecordLayer.sendFlight  (/opt/iobroker/node_modules/node-dtls-client/build/DTLS/RecordLayer.js:69:24)
host.bananapi | 2018-04-16 20:15:36.750 | error | Caught by controller[0]:     at Socket.send (dgram.js:339:11)
host.bananapi | 2018-04-16 20:15:36.749 | error | Caught by controller[0]: RangeError: Port should be > 0 and < 65536
tradfri.0 | 2018-04-16 20:15:36.465 | info | starting. Version 1.1.10 in /opt/iobroker/node_modules/iobroker.tradfri, node: v6.14.1
host.bananapi | 2018-04-16 20:15:31.293 | info | instance system.adapter.tradfri.0 started with pid 12204

**Comment by AlCalzone** [comment]
Thanks for the report. It's not a problem with the adapter itself but one if its components I've written.
I'll look into it - no guarantees to when I'll have the time though.

**Comment by AlCalzone** [comment]
I finally had some time to look into this. I'm not entirely sure whats going on. The line throwing the error already made problems a while back because the function signature changed between NodeJS versions. Are you sure that you don't have 2 different node versions installed on your system?

**Comment by axelrathey** [comment]
Hi,
I'm not sure whether there are 2 different nodejs version installed. How can I check this. There are currently no updates available said apt-get upgrade. Webmin says only one nodejs  6.14.2-1nodesource1

Thanks Axel

**Comment by AlCalzone** [comment]
I don't know actually. You could try to install the newest version of the adapter (1.2.1).
If for some reason the incorrect port gets passed from the adapter to the library, you will now get a different error message.
If it's still the same, the error has to do with the incompatible function signature.

**Comment by AlCalzone** [comment]
Anything new?

**Comment by axelrathey** [comment]
Hi,
Sorry there was a lot to do last days.

I now get the following errors from the tradfri adapter, version 1.2.1 is installed. Node is version 6.14.2
Please see the logging below.

Axel




tradfri.0 | 2018-05-14 19:52:35.308 | error | An unknown error occured while connecting to the gateway
-- | -- | -- | --
tradfri.0 | 2018-05-14 19:52:35.304 | error | Could not authenticate with the gateway 192.168.0.246/gw-b8d7af2bca01!
tradfri.0 | 2018-05-14 19:52:35.253 | info | startfile = /opt/iobroker/node_modules/iobroker.tradfri/main.js
tradfri.0 | 2018-05-14 19:52:34.969 | info | starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.tradfri, node: v6.14.2

**Comment by AlCalzone** [comment]
You have provided both an IP address and a hostname: 
> 192.168.0.246/gw-b8d7af2bca01

Use one or the other (whatever works)

**Comment by axelrathey** [comment]
Ok, that was it. Thankyou

Axel
