### ISSUE TITLE
found unknown property with key 9109

### ISSUE THREAD

**Issue by Baenker** [AlCalzone/ioBroker.tradfri#511]
Habe heute ein paar Fehler im Log. Ich würde ja fast vermuten das es ein Update gab. Die Frage ist ob ich die Fehler ignorieren kann oder ob von Deiner Seite eine Anpassung nötig ist?

Die Rollos sind 2 Stunden später ganz normal wegen Sonne runter gefahren. Das Log ist seit 10:00 Uhr auch wieder unauffällig.

tradfri.0 | 2020-11-25 09:58:36.021 | warn | (1239) object was: {"9001":"FOCUS","9002":1570542102,"9003":196613,"9057":2,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"5536":0,"9003":65546},{"5536":0,"9003":65547},
-- | -- | -- | --
tradfri.0 | 2020-11-25 09:58:36.021 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:26.280 | warn | (1239) object was: {"9001":"FOCUS","9002":1570542102,"9003":196613,"9057":2,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"9003":65545},{"5536":0,"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:26.280 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:26.112 | warn | (1239) object was: {"9001":"RELAX","9002":1570542102,"9003":196612,"9057":1,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"5536":0,"9003":65546},{"5536":0,"9003":65547},
tradfri.0 | 2020-11-25 09:58:26.112 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:25.981 | warn | (1239) object was: {"9001":"RELAX","9002":1570542102,"9003":196612,"9057":1,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"5536":0,"9003":65546},{"9003":65547},{"5536":0
tradfri.0 | 2020-11-25 09:58:25.981 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:25.779 | warn | (1239) object was: {"9001":"FOCUS","9002":1570542102,"9003":196613,"9057":2,"9068":1,"9109":0,"15016":[{"9003":65544},{"9003":65545},{"5536":0,"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:25.779 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:25.729 | warn | (1239) object was: {"9001":"RELAX","9002":1570542102,"9003":196612,"9057":1,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"5536":0,"9003":65546},{"9003":65547},{"9003":6
tradfri.0 | 2020-11-25 09:58:25.728 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:25.195 | warn | (1239) object was: {"9001":"RELAX","9002":1570542102,"9003":196612,"9057":1,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:25.195 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:25.023 | warn | (1239) object was: {"9001":"RELAX","9002":1570542102,"9003":196612,"9057":1,"9068":1,"9109":0,"15016":[{"9003":65544},{"5536":0,"9003":65545},{"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:25.023 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:24.057 | warn | (1239) object was: {"9001":"EVERYDAY","9002":1570542102,"9003":196611,"9057":0,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"5536":0,"9003":65546},{"5536":0,"9003":6554
tradfri.0 | 2020-11-25 09:58:24.057 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:23.905 | warn | (1239) object was: {"9001":"EVERYDAY","9002":1570542102,"9003":196611,"9057":0,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"5536":0,"9003":65546},{"9003":65547},{"5536
tradfri.0 | 2020-11-25 09:58:23.904 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:23.716 | warn | (1239) object was: {"9001":"EVERYDAY","9002":1570542102,"9003":196611,"9057":0,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"5536":0,"9003":65546},{"9003":65547},{"9003
tradfri.0 | 2020-11-25 09:58:23.716 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:23.190 | warn | (1239) object was: {"9001":"EVERYDAY","9002":1570542102,"9003":196611,"9057":0,"9068":1,"9109":0,"15016":[{"5536":0,"9003":65544},{"5536":0,"9003":65545},{"9003":65546},{"9003":65547},{"9003":65548}]
tradfri.0 | 2020-11-25 09:58:23.190 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:22.931 | warn | (1239) object was: {"9001":"EVERYDAY","9002":1570542102,"9003":196611,"9057":0,"9068":1,"9109":0,"15016":[{"9003":65544},{"5536":0,"9003":65545},{"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:22.930 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:22.746 | info | (1239) updating possible scenes for group 131075: ["196614"]
tradfri.0 | 2020-11-25 09:58:22.743 | warn | (1239) object was: {"9001":"ALLOFF","9002":1606294642,"9003":196614,"9057":0,"9068":3,"9109":0}
tradfri.0 | 2020-11-25 09:58:22.742 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:22.715 | warn | (1239) object was: {"9001":"FOCUS","9002":1570542102,"9003":196613,"9057":2,"9068":1,"9109":0,"15016":[{"9003":65544},{"9003":65545},{"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:22.715 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:22.672 | warn | (1239) object was: {"9001":"RELAX","9002":1570542102,"9003":196612,"9057":1,"9068":1,"9109":0,"15016":[{"9003":65544},{"9003":65545},{"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:22.672 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:22.628 | warn | (1239) object was: {"9001":"EVERYDAY","9002":1570542102,"9003":196611,"9057":0,"9068":1,"9109":0,"15016":[{"9003":65544},{"9003":65545},{"9003":65546},{"9003":65547},{"9003":65548}]}
tradfri.0 | 2020-11-25 09:58:22.627 | warn | (1239) found unknown property with key 9109
tradfri.0 | 2020-11-25 09:58:22.588 | info | (1239) got all scenes in group 131075: [196614]
tradfri.0 | 2020-11-25 09:58:22.562 | info | (1239) got all scenes in group 131074: [196611,196612,196613]
tradfri.0 | 2020-11-25 09:58:22.291 | info | (1239) got all groups: [131074,131075]
tradfri.0 | 2020-11-25 09:58:22.245 | info | (1239) got all devices: [65542,65541,65546,65545,65548,65547,65544]
pushover.3 | 2020-11-25 09:58:22.225 | info | (765) Send pushover notification: {"device":"TPhone","message":"Der Adapter läuft wieder.","title":"Tradfri-Adapter","priority":-1,"html":1}
tradfri.0 | 2020-11-25 09:58:22.219 | info | (1239) Connection to gateway reestablished
pushover.1 | 2020-11-25 09:58:00.955 | info | (735) Send pushover notification: {"device":"TPhone","message":"<font color=\"red\">Der Adapter funktioniert derzeit nicht.</font>","title":"Tradfri-Adapter","priority":1,"html":1}
tradfri.0 | 2020-11-25 09:57:00.950 | warn | (1239) Lost connection to gateway
tradfri.0 | 2020-11-25 09:56:53.747 | info | (1239) got all scenes in group 131074: [196611,196612,196613]
tradfri.0 | 2020-11-25 09:56:53.602 | info | (1239) updating possible scenes for group 131074: ["196611","196612","196613"]
tradfri.0 | 2020-11-25 09:56:53.546 | error | (1239) Error: unexpected response (5.00) to observeGroups(): [object Object]
tradfri.0 | 2020-11-25 09:56:53.537 | error | (1239) Error: unexpected response (5.00) to observeDevices(): [object Object]

**Comment by AlCalzone** [comment]
Danke, schau ich mir an.

**Comment by Grothesk242** [comment]
Da hat es ein Upgrade im Gateway und in der Tradfri App gegeben. Neu sind jetzt Szenen. Voreingestellt sind 
ALLOFF; RELAX; FOCUS; EVERYDAY

**Comment by AlCalzone** [comment]
Szenen gibt es mindestens seit 2017.

**Comment by Grothesk242** [comment]
Ja, aber das Handling wurde geändert. Es gibt ja auch einen neuen Hardware-Schalter, der genau für die Szenensteuerung zuständig ist.

**Comment by AlCalzone** [comment]
Ich hab noch keinen Unterschied festgestellt. Nutze die App aber auch fast nie.

**Comment by Grothesk242** [comment]
Dann schau mal. In der App sind die Szenen jetzt prominent auf der Startseite, mit den genannten vorgefertigten Szenen.

**Comment by FabianHM** [comment]
> 
> 
> Dann schau mal. In der App sind die Szenen jetzt prominent auf der Startseite, mit den genannten vorgefertigten Szenen.

Ich kann die zahlreichen Warnings im Log nach jedem Neutart nur bestäigen. Scheint tasächlich vom App Update letzte Woche zu kommen.
Könnte man ggf. in der Adapter Konfig ein Chekbox aufnehmen "Disable Szenes" für Nutzer die diese ganzen Szenen etc überhaupt nicht nutzen (wollen) , damit könnte man vermeiden, dass der Adapter nun ständig Warnings wirft..

Da das zu diesem Adapter mein erster Post ist aber zunächt mal das poitive Feedbck, das er ansonsten genau das macht was er soll, ohne Schnik Schnack und stabil läuft!
Danke dafür.

Viele Grüße
Fabian

**Comment by AlCalzone** [comment]
Ah - jetzt hab ich auch ein Update der App bekommen. Ich müsste auch schon alle Daten haben, die ich zum Beheben brauche: https://github.com/AlCalzone/node-tradfri-client/issues/437

**Comment by AlCalzone** [comment]
Fixed in `v2.6.4` (in Kürze verfügbar)

**Comment by FabianHM** [comment]
> 
> 
> Fixed in `v2.6.4` (in Kürze verfügbar)

Prima, vielen Dank!
