### ISSUE TITLE
Instance can't start after update to TrueNAS-12.0-U2

### ISSUE THREAD

**Issue by Herakus** [AlCalzone/ioBroker.tradfri#545]
Hello, its looks like the main programmer of this adapter speaks German, so I wrote this issue in German. If needed I can translate it to English, but for better communication I prefer the German language.

Moin, ich habe letzte Woche meine FreeNAS von Version 11.3-U5 auf TrueNAS-12.0-U2 aktualisiert. Das Jail mit ioBroker ist noch nicht aktualisiert und läuft mit Version 11.3-RELEASE-p11. Eigentlich hat sich am Jail also nichts geändert, doch nach dem update starten 2 von ca. 30 Instanzen nicht mehr. Eine davon war eine hm-rpc Instanz. Diese konnte ich wieder normal starten, nachdem ich die "Adapter Adresse" von "[IPv4] 0.0.0.0 - Auf alle IPs hören" auf "[IPv4] 192.168.0.21 - epair0b" umgestellt habe. Den tradfri Adapter konnte ich bis jetzt leider nicht wieder zum Leben erwecken. Womöglich hat sich etwas an den Netzwerkadaptern geändert, was jetzt Probleme verursacht. Aus dem Logging kann ich nur erkennen, dass die Tradfri Instanz auch die Adresse 0.0.0.0 verwendet. Vermutlich hat der Adapter somit das gleiche Problem wie der hm-rpc Adapter, nur das ich es für Tradfri nicht umstellen kann. Leider habe ich auch keinen Ansatz, wo ich auf der TrueNAS nach dem Fehler suchen könnte. Vielleicht hat noch jemand eine Idee für mich. Ansonsten wäre wohl womöglich die einfachste Lösung den Tradfri Adapter auch auf die eigene IP umzustellen.

ioBroker log:

```
tradfri.0 | 2021-02-17 21:32:48.157 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
tradfri.0 | 2021-02-17 21:32:48.157 | error | at /opt/iobroker/node_modules/mdns-server/index.js:71:17
tradfri.0 | 2021-02-17 21:32:48.157 | error | at processInterface (/opt/iobroker/node_modules/mdns-server/index.js:61:22)
tradfri.0 | 2021-02-17 21:32:48.157 | error | (11074) Error: No sockets created.
tradfri.0 | 2021-02-17 21:32:48.156 | error | (11074) unhandled promise rejection: No sockets created.
tradfri.0 | 2021-02-17 21:32:48.156 | info | (11074) Terminated (ADAPTER_REQUESTED_TERMINATION): unhandled promise rejection
tradfri.0 | 2021-02-17 21:32:48.155 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
tradfri.0 | 2021-02-17 21:32:48.155 | error | at /opt/iobroker/node_modules/mdns-server/index.js:71:17
tradfri.0 | 2021-02-17 21:32:48.155 | error | at processInterface (/opt/iobroker/node_modules/mdns-server/index.js:61:22)
tradfri.0 | 2021-02-17 21:32:48.155 | error | > stack: Error: No sockets created.
tradfri.0 | 2021-02-17 21:32:48.155 | error | (11074) unhandled promise rejection:No sockets created.
tradfri.0 | 2021-02-17 21:32:48.147 | info | (11074) Discovering the gateway automatically...
tradfri.0 | 2021-02-17 21:32:48.015 | info | (11074) starting. Version 2.6.5 in /opt/iobroker/node_modules/iobroker.tradfri, node: v12.16.1, js-controller: 3.1.6
tradfri.0 | 2021-02-17 21:32:47.301 | debug | (11074) statesDB connected
tradfri.0 | 2021-02-17 21:32:47.300 | debug | (11074) States connected to redis: 0.0.0.0:9000
tradfri.0 | 2021-02-17 21:32:47.293 | debug | (11074) States create System PubSub Client
tradfri.0 | 2021-02-17 21:32:47.291 | debug | (11074) States create User PubSub Client
tradfri.0 | 2021-02-17 21:32:47.285 | debug | (11074) Redis States: Use Redis connection: 0.0.0.0:9000
tradfri.0 | 2021-02-17 21:32:47.284 | debug | (11074) objectDB connected
tradfri.0 | 2021-02-17 21:32:47.279 | debug | (11074) Objects connected to redis: 0.0.0.0:9001
tradfri.0 | 2021-02-17 21:32:47.265 | debug | (11074) Objects client initialize lua scripts
tradfri.0 | 2021-02-17 21:32:47.264 | debug | (11074) Objects create User PubSub Client
tradfri.0 | 2021-02-17 21:32:47.263 | debug | (11074) Objects create System PubSub Client
tradfri.0 | 2021-02-17 21:32:47.261 | debug | (11074) Objects client ready ... initialize now
tradfri.0 | 2021-02-17 21:32:47.238 | debug | (11074) Redis Objects: Use Redis connection: 0.0.0.0:9001
```

**Comment by AlCalzone** [comment]
Ich fürchte das geht nicht ganz so einfach, da Tradfri unter der Haube mDNS nutzt, um das Gateway zu finden. Du könntest statt der automatischen Suche festlegen, unter welcher Adresse das Gateway erreichbar ist.

**Comment by Herakus** [comment]
Das hatte ich auch schon getestet, aber scheinbar hat sich leider ein Tippfehler in die IP-Adresse eingeschlichen. Ein Zeichen zu wenig in der IP, hat mich jetzt schon wieder einen ganzen Tag gekostet. Ach, ist das doch immer wieder schön :)
Aber trotzdem sehr merkwürdig warum die automatische Erkennung auf einmal nicht mehr funktioniert. 
Vielen Dank für den Hinweis, der Adapter funktioniert jetzt erstmal wieder. 
Hast du noch eine Idee in welche Richtung der Fehler gehen könnte? Stört mich schon zu wissen das irgendetwas auf meinem Host nicht stimmt. Ansonsten hoffe ich einfach auf die nächsten Updates von TrueNAS.

**Comment by AlCalzone** [comment]
Ich kann mir nur vorstellen, dass Ports nicht mehr freigegeben sind, oder ein anderer DNS-Dienst läuft, der mDNS blockiert, etc...

**Comment by Herakus** [comment]
Ok, vielen Dank für die Hilfe. Ich werde mal in die Richtung weiter forschen.
