### ISSUE TITLE
Admin v2 is no longer supported. Please update to Admin v3 or newer!

### ISSUE THREAD

**Issue by axelrathey** [AlCalzone/ioBroker.tradfri#55]
Hi,

I have admin version 3.4.3 (latest) installed and I get the above error with tradfri version 2.0

'Admin v2 is no longer supported. Please update to Admin v3 or newer!'

Then a dialogbox came up with the text 

'Please implement save function in your admin/index.html'

and an OK button.

What ist going wrong there?

Alternatively from which url can I download version 1.4.0 or 1.4.1? As you told on your github page this is the latest version running with admin v2

Thanks

Axel

**Comment by AlCalzone** [comment]
Well, you installed an unreleased version from github. In general, you should **never** install an adapter from github unless asked to do so by the developer. 

You should be able to fix that by executing an upload on the adapter, either by running `iobroker upload tradfri` on the console or pressing the button in the adapter list.

The 2nd way would be installing a specific version from the admin UI:
![unbenannt](https://user-images.githubusercontent.com/17641229/40019682-3be7b840-57c0-11e8-80a6-e85829f14d65.PNG)

**Comment by AlCalzone** [comment]
Any news? Did the proposed fixes work?

**Comment by axelrathey** [comment]
Sorry, the iobroker upload tradfri worked. Now version 2.0.0 works without problem for me.

Axel
