### ISSUE TITLE
Getting events from Tradfri buttons

### ISSUE THREAD

**Issue by sunsear** [AlCalzone/ioBroker.tradfri#557]
I would love to be able to do something when one of my Tradfri buttons was pressed. I can see the switches In my objects list, but they have no actionable properties. Would it be possible to add something like that?

**Comment by AlCalzone** [comment]
Nope, see previous issues requesting the same. The gateway doesn't give us that info.
https://github.com/AlCalzone/ioBroker.tradfri/issues/446
https://github.com/AlCalzone/ioBroker.tradfri/issues/278

**Comment by sunsear** [comment]
I was afraid of that, but couldn't find it as I was searching in English. Thanks @AlCalzone , for clearing that up.
