### ISSUE TITLE
Helligkeit %-Zahlen werden als Float im Request abgesetzt

### ISSUE THREAD

**Issue by drbugfinder** [AlCalzone/iobroker.tradfri#6]
Hi,

nachdem ich gemerkt habe, dass Alexa die Tradfri Lampen nur mit 0, 50 und 100% steuern konnte schaute ich mir den Code an. Bitte in der main.js entsprechend runden. Siehe hier:
`                                // TODO: find a way to construct these from existing accessory objects
 _global2.default.log("drbugfinder was here");                               
var payload = null;
if (id.endsWith(".lightbulb.state")) {
                                        val = Math.round(val);
payload = { "3311": [{ "5850": val ? 1 : 0 }] };
} else if (id.endsWith(".lightbulb.brightness")) {
                                        val = Math.round(val);
payload = { "3311": [{ "5851": val, "5712": 5 }] };
} else if (id.endsWith(".lightbulb.color")) {
var colorX = _conversions2.default.color("out", state.val);
payload = { "3311": [{ "5709": colorX, "5710": 27000, "5712": 5 }] };
}
`
Dann passt es!

**Comment by AlCalzone** [comment]
Ich überlege, statt 0-254 für die Helligkeit 0-100 (also direkt in %) in ioBroker zur Verfügung zu stellen. Dann sollte das Problem auch gelöst sein. Aber guter Hinweis, das sollte natürlich abgefangen werden.
