### ISSUE TITLE
tradfri nach Update auf 3.0.0 keine Verbindung mehr

### ISSUE THREAD

**Issue by betonix70** [AlCalzone/ioBroker.tradfri#646]
Hallo,

bisher lief auf meinem IoBroker der tradfri Adapter absolut problemlos. Nach dem Update auf die Version 3.0.o meldet er in den Protokollen "failed connection attempt"
In den Instanzen steht der Adapter mit einem gelben Ausrufezeichen "Verbunden mit Gerät oder Dienst" ist nicht aktiv (rotes Kreuz)

Alle Möglichkeiten die mir bekannt sind (Neustart, Aktualisieren, IoBroker komplett neu starten, IKEA Gateway neu starten) habe ich durch.

Eventuell kann mir ja jemand helfen....

**Comment by AlCalzone** [comment]
Update auf 3.0.1 hilft :)

**Comment by AlCalzone** [comment]
https://github.com/AlCalzone/ioBroker.tradfri/issues/637#issuecomment-872073445

**Comment by betonix70** [comment]
Danke für die schnelle Hilfe :-)
Ich würde ja gerne auf 3.0.1 gehene. Nur wird der bei mir leider nicht angezeigt?
Keine Ahnung warum.
Im Info Bereich ist tatsächlich die Meldung vorhanden.
Aber wie gesagt, wäre die Version 3.0.1 bei mir vorhanden hätte ich sie auch installiert.
kann man die auch direkt installieren?

**Comment by betonix70** [comment]
Sorry habe den Link übersehen.

Hat geklappt und funktioniert. Danke!
