### ISSUE TITLE
Keine Verbindung trotz Update auf 3.0.1

### ISSUE THREAD

**Issue by aXCell-fl** [AlCalzone/ioBroker.tradfri#659]
Hallo, 
leider bekomme ich partus keine Verbindung zum Tradfri Gateway. Der Status bleibt immer "gelb".

ioBroker Admin: 4.2.2
Node.js: v14.17.4
NPM: 6.14.14
Der IoBroker läuft auf einem Mac mit Catalina 10.15.7
JS controller: 3.2.16

Ob nur IP, Kombination aus IP/gw-MAC ADRESSE oder nur gw-MAC ADRESSE …. nichts, einen fehlerhaften Security Code kann ich nahezu ausschliessen, da kein "o" oder "0" oder "L" oder "i" zum vertauschen im Code sind.
Dennoch kommt immer im LOG diese Fehlermeldung:

Das IKEA Gateway ist per Ethernet Kabel direkt an der FritzBox, der Mac ist im 5GhZ WLAN der FritzBox. Das Gateway darf stelbstständig Ports verwalten, die IP ist fest zugewiesen.

![Bildschirmfoto 2021-08-01 um 22 09 58](https://user-images.githubusercontent.com/88290030/127784117-3e47e1db-30a5-442d-8056-ffca692bc2f1.png)

```
| error | (49309) Please check your adapter settings and restart the adapter!
| error | (49309) The security code is incorrect or something else went wrong with the authentication.
| error | (49309) Please check your network and adapter settings and restart the adapter!
| error | (49309) The gateway 192.168.###.## is unreachable or did not respond in time!
| info | (52309) Found gateway gw-c4ac######3d at 192.168.###.##
| info | (52309) Discovering the gateway automatically...
| info | (52309) starting. Version 3.0.1 in /usr/local/iobroker/node_modules/iobroker.tradfri, node: v14.17.4, js-controller: 3.2.16



```

Ich weiß nicht, was ich noch testen / ändern könnte, das der Adapter das Gateway annimmt.

Was wird noch zur Hilfe benötigt?

Gruß, aXCell

**Comment by AlCalzone** [comment]
Kannst du mal den Adapter auf Loglevel "debug" schalten und nochmal ein Log posten?
Ggf. sieht man da schon was los ist.

**Comment by aXCell-fl** [comment]
Hallo. 
Selbstverständlich gerne, wenn du mir verrätst, wie ich den Loglevel auf "debug" schalte.

**Comment by AlCalzone** [comment]
1. In der Instanz-Liste den Expertenmodus aktivieren
2. in der Spalte "Log-Stufe" auf "info" klicken
3. im Dropdown "debug" auswählen

**Comment by aXCell-fl** [comment]
Danke für die Erklärung!

Das ist der debug Log, direkt nach Neustarten des Adapters

```
tradfri.0 | 2021-08-02 12:45:03.324 | error | (53924) Please check your adapter settings and restart the adapter!
tradfri.0 | 2021-08-02 12:45:03.324 | error | (53924) The security code is incorrect or something else went wrong with the authentication.
tradfri.0 | 2021-08-02 12:45:03.324 | error | (53924) Please check your network and adapter settings and restart the adapter!
tradfri.0 | 2021-08-02 12:45:03.324 | error | (53924) The gateway 192.168.178.45 is unreachable or did not respond in time!
tradfri.0 | 2021-08-02 12:45:03.323 | debug | (53924) Connection failed. Reason: timeout
tradfri.0 | 2021-08-02 12:45:00.313 | debug | (53924) Attempting connection. Identity = Client_identity, psk = k94We2FeKRFNanu7
tradfri.0 | 2021-08-02 12:45:00.312 | debug | (53924) authenticate() > trying to connect with the security code
tradfri.0 | 2021-08-02 12:45:00.309 | info | (53924) Found gateway gw-c4ac59eb053d at 192.168.178.45
tradfri.0 | 2021-08-02 12:45:00.256 | info | (53924) Discovering the gateway automatically...
tradfri.0 | 2021-08-02 12:45:00.219 | info | (53924) starting. Version 3.0.1 in /usr/local/iobroker/node_modules/iobroker.tradfri, node: v14.17.4, js-controller: 3.2.16
tradfri.0 | 2021-08-02 12:45:00.103 | debug | (53924) statesDB connected
tradfri.0 | 2021-08-02 12:45:00.102 | debug | (53924) States connected to redis: 127.0.0.1:9000
tradfri.0 | 2021-08-02 12:45:00.099 | debug | (53924) States create User PubSub Client
tradfri.0 | 2021-08-02 12:45:00.099 | debug | (53924) States create System PubSub Client
tradfri.0 | 2021-08-02 12:45:00.095 | debug | (53924) Redis States: Use Redis connection: 127.0.0.1:9000
tradfri.0 | 2021-08-02 12:45:00.094 | debug | (53924) objectDB connected
tradfri.0 | 2021-08-02 12:45:00.089 | debug | (53924) Objects connected to redis: 127.0.0.1:9001
tradfri.0 | 2021-08-02 12:45:00.080 | debug | (53924) Objects client initialize lua scripts
tradfri.0 | 2021-08-02 12:45:00.080 | debug | (53924) Objects create User PubSub Client
tradfri.0 | 2021-08-02 12:45:00.079 | debug | (53924) Objects create System PubSub Client
tradfri.0 | 2021-08-02 12:45:00.078 | debug | (53924) Objects client ready ... initialize now
tradfri.0 | 2021-08-02 12:45:00.056 | debug | (53924) Redis Objects: Use Redis connection: 127.0.0.1:9001
tradfri.0 | 2021-08-02 12:44:56.532 | info | (47451) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tradfri.0 | 2021-08-02 12:44:56.532 | info | (47451) terminating
tradfri.0 | 2021-08-02 12:44:56.531 | info | (47451) Got terminate signal TERMINATE_YOURSELF
tradfri.0 | 2021-08-02 11:49:10.718 | error | (47451) Please check your adapter settings and restart the adapter!
tradfri.0 | 2021-08-02 11:49:10.717 | error | (47451) The security code is incorrect or something else went wrong with the authentication.
tradfri.0 | 2021-08-02 11:49:10.717 | error | (47451) Please check your network and adapter settings and restart the adapter!
tradfri.0 | 2021-08-02 11:49:10.717 | error | (47451) The gateway 192.168.178.45 is unreachable or did not respond in time!
tradfri.0 | 2021-08-02 11:49:07.689 | info | (47451) Found gateway gw-c4ac59eb053d at 192.168.178.45
tradfri.0 | 2021-08-02 11:49:07.621 | info | (47451) Discovering the gateway automatically...
tradfri.0 | 2021-08-02 11:49:07.596 | info | (47451) starting. Version 3.0.1 in /usr/local/iobroker/node_modules/iobroker.tradfri, node: v14.17.4, js-controller: 3.2.16
tradfri.0 | 2021-08-02 11:49:03.912 | info | (52309) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tradfri.0 | 2021-08-02 11:49:03.912 | info | (52309) terminating
tradfri.0 | 2021-08-02 11:49:03.904 | info | (52309) Got terminate signal TERMINATE_YOURSELF

```

**Comment by AlCalzone** [comment]
Hm, ich schätze das hilft nicht. Kannst du bitte das aus dem folgenden Post versuchen?
https://github.com/AlCalzone/ioBroker.tradfri/issues/454#issuecomment-677291762

Die Datei und deine Schlüssel kannst du mir per E-Mail schicken. Siehe Readme ganz unten.

**Comment by aXCell-fl** [comment]
Die Daten sind unterwegs.

**Comment by AlCalzone** [comment]
Irgendwas ist da faul bei dir. Das Gateway antwortet schlichtweg nicht richtig. Zwischen jedem dieser 3 Versuche liegt 1 Sekunde, dann gibt der Adapter auf.
![grafik](https://user-images.githubusercontent.com/17641229/127868574-029485c5-1efc-4ad8-b91d-7b987904dc6d.png)

Bei mir geht es ohne Umstände weiter:
![grafik](https://user-images.githubusercontent.com/17641229/127869724-eef40d97-f38d-462a-b40c-e6e121e99123.png)

Woran das liegt, kann ich dir leider nicht sagen.

**Comment by aXCell-fl** [comment]
Mist, wie komme ich dem denn nun auf die Schliche....
Vielen Dank für deine Bemühungen!

**Comment by AlCalzone** [comment]
Nur zur Sicherheit: Welche Version läuft auf deinem Gateway?
Und hast du noch irgendwelche Apps, die gleichzeitig drauf zugreifen?

**Comment by aXCell-fl** [comment]
Das Gateway hat Version 1.15.34
Darauf zugreifen 
- Ikea Home Smart App
- Alexa per Skill
- und der ioBroker versucht es.

**Comment by AlCalzone** [comment]
> Das Gateway hat Version 1.15.34

Ok meins auch.

> Darauf zugreifen ...

Das könnte 1 zu viel sein. Bei mir haut es jedes Mal die App raus, wenn ich den Adapter nutze. Anscheinend ist das Gateway da pingelig geworden.

**Comment by aXCell-fl** [comment]
Guten Morgen. 

Aber dann müssten doch viel mehr das Problem haben, die die App und Homkit und Alexa oder die Apo, Alexa und Google zeitgleich nutzen. 
Das erklärt sich mir nicht ganz.

**Comment by AlCalzone** [comment]
Ich hatte erst vorgestern jemand, dessen Adapter plötzlich lief nachdem er sich von der App abgemeldet hat.
Daher der Hinweis.

**Comment by aXCell-fl** [comment]
Ok. 
Mit dem Hintergrund hat das schon ein anderes Gewicht. 
Aber es gibt ja auch viele, bei denen der Adapter auch mit z. B.  4 Diensten gleichzeitig läuft, denke ich. 

Aber ich werde mal Alexa kicken. 

Danke für deinen Support!

**Comment by aXCell-fl** [comment]
Kurze Info: 

Ich habe die App erst getrennt, dann auch gelöscht.
Zusätzlich den Alexa Skill deaktiviert und gelöscht. 
Leider weiterhin keine Verbindung.

**Comment by Baenker** [comment]
Es gab heute ein Update auf die 1.15.55 vielleicht hast Du damit Glück. Ich würde sonst mal gucken was passiert wenn Du das Gateway mal zurücksetzt.

Bei mir läuft alles (aber auch schon mit der alten Gateway Firmware). Sowohl per ioBroker als auch per App. Wobei ich die App nur selten nutze. Homekit habe ich eingebunden aber eigentlich nie verwendet nur beim einrichten.

**Comment by AlCalzone** [comment]
@aXCell-fl Mal ganz anders: haste mal beim Gateway den Strom getrennt und es so hart neu gestartet?

**Comment by aXCell-fl** [comment]
Leider ja, mehrfach bereits. Auch den Router und den Mac, alles was per Stromreset zu reseten war, hat mindestens einen Neustart erhalten.

**Comment by AlCalzone** [comment]
@aXCell-fl eine Idee hätte ich noch:
Objekt `system.adapter.tradfri.0` bearbeiten (Expertenmodus), dort im Reiter "nativ" die Einträge aus `identity` und `psk` entfernen. `securityCode` muss stehen bleiben.

**Comment by aXCell-fl** [comment]
Leider wieder keine Verbindung :-( 
Habe das Gateway vom Strom getrennt, die Werte gelöscht und die Instanz dann neu gestartet, danach das Gateway an Strom angeschlossen.

Ergebnis:

```
| error | (19096) Please check your adapter settings and restart the adapter!
| error | (19096) The security code is incorrect or something else went wrong with the authentication.
| error | (19096) Please check your network and adapter settings and restart the adapter!
| error | (19096) The gateway gw-c4ac59eb053d is unreachable or did not respond in time!
```

**Comment by AlCalzone** [comment]
Kannst du mir davon nochmal einen tcpdump machen? Vielleicht sieht man da was

**Comment by aXCell-fl** [comment]
Die gleiche Situation nochmal nachstellen und dann im Anschluss ein dump erstellen? 
Mache ich dann morgen.

**Comment by aXCell-fl** [comment]
Sorry, habe es gestern nicht mehr geschafft.
Ein neuer Dump ist gerade auf dem Weg per Mail zu dir, die Daten hast du ja noch, bzw. sind im Verlauf der Mail ersichtlich.

Ich danke dir!

**Comment by AlCalzone** [comment]
Fürchte das hat keine Änderung gebracht. Ich bin ratlos 🤷🏻‍♂️

**Comment by aXCell-fl** [comment]
Schade, ich war voller Hoffnung 

Trotzdem Danke für deine großartige Hilfe!

**Comment by AlCalzone** [comment]
Wenn es nicht allzu viel Aufwand ist, könntest du noch versuchen, das Gateway komplett zurück zu setzen.

**Comment by aXCell-fl** [comment]
Das werde ich zeitnah machen, verliere zwar dann temporär alles aus dem HomeKit, daher wahrscheinlich erst Sonntag, wenn ich Zeit finde, das wieder alles neu mit dem Gateway zu verknüpfen.

P.S. Mich interessiert es jetzt schon sehr, warum es gerade hier nicht klappt, wenn es bei allen anderen doch geht. So besonders kann meine Konfiguration ja eigtl. nicht sein, als reiner Anwender.

**Comment by aXCell-fl** [comment]
So, @AlCalzone 

Ich habe das Gateway zurückgesetzt und dann erneut versucht, das quasi nackte Gateway mit dem ioBroker zu verbinden.
Fehlanzeige, gleiche Meldungen wie zuvor.

Log debug:
```
tradfri.0 | 2021-08-08 15:12:49.658 | error | (59327) Please check your adapter settings and restart the adapter!
tradfri.0 | 2021-08-08 15:12:49.658 | error | (59327) The security code is incorrect or something else went wrong with the authentication.
tradfri.0 | 2021-08-08 15:12:49.658 | error | (59327) Please check your network and adapter settings and restart the adapter!
tradfri.0 | 2021-08-08 15:12:49.658 | error | (59327) The gateway 192.168.178.45 is unreachable or did not respond in time!
tradfri.0 | 2021-08-08 15:12:49.657 | debug | (59327) Connection failed. Reason: timeout
tradfri.0 | 2021-08-08 15:12:48.673 | debug | (59327) system.adapter.admin.0: logging true
tradfri.0 | 2021-08-08 15:12:46.640 | debug | (59327) Attempting connection. Identity = Client_identity, psk = k94We2FeKRFNanu7
tradfri.0 | 2021-08-08 15:12:46.638 | debug | (59327) authenticate() > trying to connect with the security code
tradfri.0 | 2021-08-08 15:12:46.636 | info | (59327) Found gateway gw-c4ac59eb053d at 192.168.178.45
tradfri.0 | 2021-08-08 15:12:46.547 | info | (59327) Discovering the gateway automatically...
tradfri.0 | 2021-08-08 15:12:46.521 | info | (59327) starting. Version 3.0.1 in /usr/local/iobroker/node_modules/iobroker.tradfri, node: v14.17.4, js-controller: 3.3.15
tradfri.0 | 2021-08-08 15:12:46.423 | debug | (59327) statesDB connected
tradfri.0 | 2021-08-08 15:12:46.423 | debug | (59327) States connected to redis: 127.0.0.1:9000
tradfri.0 | 2021-08-08 15:12:46.420 | debug | (59327) States create User PubSub Client
tradfri.0 | 2021-08-08 15:12:46.419 | debug | (59327) States create System PubSub Client
tradfri.0 | 2021-08-08 15:12:46.416 | debug | (59327) Redis States: Use Redis connection: 127.0.0.1:9000
tradfri.0 | 2021-08-08 15:12:46.415 | debug | (59327) objectDB connected
tradfri.0 | 2021-08-08 15:12:46.411 | debug | (59327) Objects connected to redis: 127.0.0.1:9001
tradfri.0 | 2021-08-08 15:12:46.403 | debug | (59327) Objects client initialize lua scripts
tradfri.0 | 2021-08-08 15:12:46.402 | debug | (59327) Objects create User PubSub Client
tradfri.0 | 2021-08-08 15:12:46.402 | debug | (59327) Objects create System PubSub Client
tradfri.0 | 2021-08-08 15:12:46.401 | debug | (59327) Objects client ready ... initialize now

```

Ein TCP dump nach Reset und beim Verbindungsversuch ist per Mail auf dem Weg zu dir.

**Comment by AlCalzone** [comment]
Keine Änderung :(

**Comment by mylargo** [comment]
Hallo @AlCalzone 

Mich hat es nun auch erwischt.



tradfri.0 | 2021-11-02 18:16:24.885 | error | Please check your adapter settings and restart the adapter!
-- | -- | -- | --
tradfri.0 | 2021-11-02 18:16:24.884 | error | The security code is incorrect or something else went wrong with the authentication.


Gateway Version: 1.16.2
ioBroker Adapter: 3.0.1
Node JS: v12.22.6
NPM: 6.14.15


Ich hatte erst die 2.7.4 und damit ab und zu Probleme, d.h. Befehle reagierten nicht etc. Deshalb bin ich, nachdem ich hier auf Github gesehen habe, es gibt eine 3.0.1 auf diese Version gegangen. Das war gestern. Es funktionierte dann auch erst, jedoch habe ich heute festgestellt das der Adapter sich ausgestellt hat und beim Einschalten kommen die oben genannten Meldungen.

Mich frustet IKEA mit ihrer Updatepolitik schon eine Weile, da mit jedem Gateway Update entweder was im iobroker knallt und/oder mind. 2-3 Lampen offline gehen und per Sicherungskasten wieder zum leben erweckt werden müssen.
Also kein Vorwurf an dich und deinen Adapter. 
Wenn du es wieder zum laufen bringst mit der aktuellen Version, werde ich das Gateway wohl für den Internetverkehr sperren, dass es keine automatischen Updates mehr zieht.

**Comment by Baenker** [comment]
Ich kann zwar nicht helfen aber bei mir hat das Gateway die Version 1.16.26. Wurde glaube ich vor ein paar Tagen eingespielt. Weiterhin keine Probleme mit dem Adapter in V3.01.

**Comment by AlCalzone** [comment]
@mylargo 2.7.4 und 3.0.1 sind funktionell identisch, benötigen aber eine andere Node.js-Version (10 bzw. 12+)

Ich kann das hier leider nicht nachvollziehen, bei mir läuft 2.7.4 mit Gateway 1.16.26 tadellos (bis auf hin und wieder eine Lampe, die nen Neustart braucht).
