### ISSUE TITLE
State value to set for "tradfri.0.B-65572.blind.stop" has to be type "boolean" but received type "function" 

### ISSUE THREAD

**Issue by Grothesk242** [AlCalzone/ioBroker.tradfri#661]
Habe die Datenpunkte komplett neueinlesen lassen, bei allen Rollos gibt es noch die Meldung.

```State value to set for "tradfri.0.B-65572.blind.stop" has to be type "boolean" but received type "function" ```

Controller "js-controller" : 3.3.15   , installed 3.3.15
Adapter    "tradfri"       : 3.0.1    , installed 3.0.1
nodejs -v 16.7.0

**Comment by jk-andersen** [comment]
Same

<html>
<body>


tradfri.0 | 2021-09-12 22:11:29.787 | info | State value to set for "tradfri.0.G-131090.stopBlinds" has to be type "boolean" but received type "function"
-- | -- | -- | --
tradfri.0 | 2021-09-12 22:11:29.754 | info | State value to set for "tradfri.0.G-131087.stopBlinds" has to be type "boolean" but received type "function"
tradfri.0 | 2021-09-12 22:11:29.724 | info | State value to set for "tradfri.0.G-131086.stopBlinds" has to be type "boolean" but received type "function"
tradfri.0 | 2021-09-12 22:11:29.685 | info | State value to set for "tradfri.0.G-131085.stopBlinds" has to be type "boolean" but received type "function"
tradfri.0 | 2021-09-12 22:11:29.623 | info | State value to set for "tradfri.0.G-131084.stopBlinds" has to be type "boolean" but received type "function"
tradfri.0 | 2021-09-12 22:11:29.584 | info | State value to set for "tradfri.0.G-131081.stopBlinds" has to be type "boolean" but received type "function"
tradfri.0 | 2021-09-12 22:11:29.547 | info | State value to set for "tradfri.0.G-131073.stopBlinds" has to be type "boolean" but received type "function"


</body>
</html>


Controller "js-controller" : 3.3.18 , installed 3.3.18
Adapter "tradfri" : 3.0.1 , installed 3.0.1
nodejs -v v 14.17.6
