### ISSUE TITLE
Unknown device type 1

### ISSUE THREAD

**Issue by gaudes** [AlCalzone/ioBroker.tradfri#69]
Hi,

with version 1.5.4 I get unkown device type:

tradfri.0 | 2018-12-02 16:25:53.978 | warn | Unknown accessory type 1. Please send this info to the developer with a short description of the device!
-- | -- | -- | --
tradfri.0 | 2018-12-02 16:25:53.977 | debug | observeDevice > {"3":{"0":"IKEA of Sweden","1":"TRADFRI remote control","2":"","3":"1.2.214","6":3,"9":74},"5750":1,"9001":"Fernbedienung Schlafzimmer","9002":1543762150,"9003":65562,"9019":1,"9020":1

It's the normal remote control, but I had to reset and reconnect it. So no problem at all, just for information.

Regards, Ralf

**Comment by AlCalzone** [comment]
Thanks for the report. 1 is a device type (slave remote) that is already recognized by the underlying library, but I forgot to include it in the adapter.
