### ISSUE TITLE
Neue Fehler im log // neue Firmware?

### ISSUE THREAD

**Issue by Baenker** [AlCalzone/ioBroker.tradfri#704]
gerade hat mein Adapter mal wieder kurz die Verbindung verloren. Meist ein Zeichen für eine neue Firmware?

Hier der Log-Auszug:

tradfri.0 | 2021-12-13 17:41:58.046 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":59}
-- | -- | -- | --
tradfri.0 | 2021-12-13 17:41:58.046 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:41:56.135 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":59}
tradfri.0 | 2021-12-13 17:41:56.135 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:41:40.097 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":70}
tradfri.0 | 2021-12-13 17:41:40.096 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:41:38.148 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":70}
tradfri.0 | 2021-12-13 17:41:38.148 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:41:23.431 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":57}
tradfri.0 | 2021-12-13 17:41:23.431 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:41:22.398 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":57}
tradfri.0 | 2021-12-13 17:41:22.398 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:41:05.232 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":42}
tradfri.0 | 2021-12-13 17:41:05.231 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:41:03.957 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":42}
tradfri.0 | 2021-12-13 17:41:03.956 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:40:41.890 | info | got all scenes in group 131075: [196614]
tradfri.0 | 2021-12-13 17:40:41.862 | info | got all scenes in group 131074: [196611,196612,196613]
tradfri.0 | 2021-12-13 17:40:41.774 | info | got all groups: [131074,131075]
tradfri.0 | 2021-12-13 17:40:41.768 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":58}
tradfri.0 | 2021-12-13 17:40:41.768 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:40:41.762 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":61}
tradfri.0 | 2021-12-13 17:40:41.761 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:40:41.755 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":55}
tradfri.0 | 2021-12-13 17:40:41.753 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:40:41.747 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":46}
tradfri.0 | 2021-12-13 17:40:41.747 | warn | found unknown property with key 8
pushover.3 | 2021-12-13 17:40:41.702 | info | Send pushover notification: {"device":"TPhone","message":"Der Adapter läuft wieder.","title":"Tradfri-Adapter","priority":-1,"html":1}
tradfri.0 | 2021-12-13 17:40:41.741 | warn | object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":77}
tradfri.0 | 2021-12-13 17:40:41.741 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:40:41.735 | warn | object was: {"0":"IKEA of Sweden","1":"TRADFRI Signal Repeater","2":"","3":"2.2.005","6":1,"7":4354,"8":0}
tradfri.0 | 2021-12-13 17:40:41.734 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:40:41.730 | warn | object was: {"0":"\u0002KE","1":"TRADFRI open/close remote","2":"","3":"2.2.010","6":3,"7":4549,"8":0,"9":100}
tradfri.0 | 2021-12-13 17:40:41.729 | warn | found unknown property with key 8
tradfri.0 | 2021-12-13 17:40:41.722 | info | got all devices: [65542,65541,65546,65547,65544,65548,65545]
tradfri.0 | 2021-12-13 17:40:41.693 | info | Connection to gateway reestablished
pushover.1 | 2021-12-13 17:40:20.417 | info | Send pushover notification: {"device":"TPhone","message":"<font color=\"red\">Der Adapter funktioniert derzeit nicht.</font>","title":"Tradfri-Adapter","priority":1,"html":1}
tradfri.0 | 2021-12-13 17:39:20.408 | warn | Lost connection to gateway

Nutze die aktuelle Version vom Adapter 3.02
Gateway 1.17.19
Er scheint die Rollos zu aktualisieren: Firmware dort 2.3.073 und dort steht aktualisieren…

Vielleicht sind die Fehler ja nur einmalig. Ich schreibe noch eine Info wenn der Fehler wieder auftritt

**Comment by Roller-HS** [comment]
Habe das gleiche Problem, seit gestern.


tradfri.0 | 2021-12-13 17:49:09.069 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI motion sensor","2":"","3":"2.0.022","6":3,"7":4552,"8":0,"9":16}
-- | -- | -- | --
tradfri.0 | 2021-12-13 17:49:09.068 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:19.616 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:46:19.616 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:16.799 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:46:16.799 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:16.754 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:46:16.754 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:15.023 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:46:15.023 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:13.334 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:46:13.333 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:13.299 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:46:13.298 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:09.148 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:46:09.147 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:46:09.125 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI motion sensor","2":"","3":"2.0.022","6":3,"7":4552,"8":0,"9":16}
tradfri.0 | 2021-12-13 17:46:09.123 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.492 | info | (12892) received all groups and scenes
tradfri.0 | 2021-12-13 17:42:43.464 | info | (12892) got all scenes in group 131081: []
tradfri.0 | 2021-12-13 17:42:43.445 | info | (12892) got all scenes in group 131080: []
tradfri.0 | 2021-12-13 17:42:43.422 | info | (12892) got all scenes in group 131079: []
tradfri.0 | 2021-12-13 17:42:43.397 | info | (12892) got all scenes in group 131078: []
tradfri.0 | 2021-12-13 17:42:43.375 | info | (12892) got all scenes in group 131073: [196608]
tradfri.0 | 2021-12-13 17:42:43.201 | info | (12892) got all groups: [131081,131078,131079,131080,131073]
tradfri.0 | 2021-12-13 17:42:43.193 | info | (12892) received all devices
tradfri.0 | 2021-12-13 17:42:43.186 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 CWS 806lm","2":"","3":"1.0.021","6":1,"7":10242,"8":4}
tradfri.0 | 2021-12-13 17:42:43.185 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.175 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI on/off switch","2":"","3":"2.3.079","6":3,"7":4549,"8":0,"9":87}
tradfri.0 | 2021-12-13 17:42:43.174 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.159 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:42:43.158 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.136 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:42:43.136 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.121 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI motion sensor","2":"","3":"2.0.022","6":3,"7":4552,"8":0,"9":74}
tradfri.0 | 2021-12-13 17:42:43.120 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.102 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 CWS 806lm","2":"","3":"1.0.021","6":1,"7":10242,"8":4}
tradfri.0 | 2021-12-13 17:42:43.102 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.083 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 CWS 806lm","2":"","3":"1.0.021","6":1,"7":10242,"8":4}
tradfri.0 | 2021-12-13 17:42:43.083 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.069 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"Remote Control N2","2":"","3":"1.0.024","6":3,"7":4555,"8":0,"9":100}
tradfri.0 | 2021-12-13 17:42:43.069 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.044 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI motion sensor","2":"","3":"2.0.022","6":3,"7":4552,"8":0,"9":87}
tradfri.0 | 2021-12-13 17:42:43.044 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.027 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI motion sensor","2":"","3":"2.0.022","6":3,"7":4552,"8":0,"9":16}
tradfri.0 | 2021-12-13 17:42:43.027 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:43.013 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI remote control","2":"","3":"2.3.080","6":3,"7":4545,"8":0,"9":87}
tradfri.0 | 2021-12-13 17:42:43.012 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:42.989 | warn | (12892) object was: {"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 1000lm","2":"","3":"2.0.029","6":1,"7":16900,"8":5}
tradfri.0 | 2021-12-13 17:42:42.988 | warn | (12892) found unknown property with key 8
tradfri.0 | 2021-12-13 17:42:42.975 | info | (12892) got all devices: [65553,65543,65542,65547,65544,65541,65537,65546,65549,65550,65554,65545]

**Comment by Grothesk242** [comment]
> Er scheint die Rollos zu aktualisieren: Firmware dort 2.3.073 und dort steht aktualisieren…

Nicht nur die Rollos. Hier geht gerade eine Update-Orgie ab. Alle möglichen Geräte bekommen neue Firmwares. Inkl. des Gateways.

**Comment by rug1024** [comment]
Habe die gleichen Meldungen im Log seit dem Firmware-Update. Der ioBroker-Tradfri-Adapter muss vom Author angepasst werden.
Hier sieht man welche Geräte alle Updates bekommen haben: https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

**Comment by Baenker** [comment]
Fehler tritt bei jeder Bedienung auf. Die Fehler die Ikea adressiert hat, hatte ich bei mir zumindest nicht :-)

**Comment by AlCalzone** [comment]
Das sind warnungen, keine Fehler. Ein paar Tage müsst ihr damit leben, bis ich zeit habe sie zu fixen.

**Comment by Grothesk242** [comment]
Log Level ist auf Error gesetzt. Grundsätzlich funktioniert alles, da kann man auch ein paar Tage mit leben.

**Comment by AlCalzone** [comment]
Sollte in v3.1.0 gefixt sein.
