### ISSUE TITLE
2x auslösen für Steckdosen und Rollos funktionieren nicht zuverlässig

### ISSUE THREAD

**Issue by Burny08** [AlCalzone/ioBroker.tradfri#740]
Hey zusammen, 

ich nutze die TRADFRI Rollos, 4 Stück an der Zahl. 3 Stück im Esszimmer, 1 im Wohnzimmer. 
Ich habe alle Rollos in iObroker eingebunden. 
Wenn ich nun mehrere Rollos ansteuern möchte (über den Yahka Adapter) fahren in der Regel immer nur zwei Rollos. 
Ich habe mir die Werte bei "position" angeschaut, die richtigen Werte werden dort auch geschrieben (also entweder 0% oder 100%) aber die Rollos fahren nicht. 
Aus der IKEA Home App heraus funktioniert alles einwandfrei, aber nicht über die Objekte. 
Gibts dafür eine Erklärung oder habe ich etwas nicht richtig eingestellt? 
Im Tradfri Adapter habe ich bereits "Preserve transition time" aktiviert/deaktiviert, aber das hat auch nichts geholfen. 

Weiterhin: Ikea Steckdosen funktionieren zwar, aber ich muss immer 2x auslösen bevor sie reagiert. 2x für an und 2x für aus. Gibts dafür auch einen Trick/Tipp? 
Danke für die Hilfe! 

Mein Setup: 
- Tradfri Gateway 1.17.22
- Tradfri Adapter in ioBroker 3.1.2 
- aktuelles ioBroker auf einem Raspberry Pi
- Steuern über Yahka Adapter/Apple HomeKit

**Comment by AlCalzone** [comment]
In der Vergangenheit gabs immer mal wieder Reports, dass das Gateway Befehle verschluckt wenn sie zu schnell kommen. Z.B. wenn eine Lampe langsam dimmt und die nächste zwischendurch schon gestartet wird. Das könnte auch hier der Fall sein.

Steuerst du die Rollos einzeln oder über eine Gruppe? Letzteres könnte das Problem beheben, weil es da nur ein Kommando gibt statt eins pro Rollo.

> Ikea Steckdosen funktionieren zwar, aber ich muss immer 2x auslösen bevor sie reagiert. 2x für an und 2x für aus. Gibts dafür auch einen Trick/Tipp?

Das müsste ich mal in nem debug-Log vom Adapter sehen.

**Comment by Burny08** [comment]
> Steuerst du die Rollos einzeln oder über eine Gruppe? Letzteres könnte das Problem beheben, weil es da nur ein Kommando gibt statt eins pro Rollo.<
 
Ja ich sende die Befehle einzeln. Ich habe mir schon gedacht das hier das Problem sein könnte. Ich bin im Skripten von iobroker nicht fit, aber gibt es eine Möglichkeit die Signale zeitlich leicht versetzt an den Gateway zu senden? Ich würde gern alle Rollos einzeln in HomeKit steuern können. Wenn ich sie in eine Gruppe werfe dann kann ich die aktuelle Position nicht mehr auslesen. 

> Steuerst du die Rollos einzeln oder über eine Gruppe? Letzteres könnte das Problem beheben, weil es da nur ein Kommando gibt statt eins pro Rollo.<

Sagst du mir fix wie ich das auslesen kann? Dann würde ich es dir schicken.

**Comment by AlCalzone** [comment]
> Sagst du mir fix wie ich das auslesen kann

In dem Instanzen-Tab das Loglevel für tradfri auf "debug" schalten. Dann findest du es im normalen ioBroker Log. Bitte nicht da rauskopieren (Zeilen zu lang) sondern die Datei runterladen.

> Ich bin im Skripten von iobroker nicht fit, aber gibt es eine Möglichkeit die Signale zeitlich leicht versetzt an den Gateway zu senden?

Ja. https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#wait - gibts auch als Blockly-Block

**Comment by Burny08** [comment]
> In dem Instanzen-Tab das Loglevel für tradfri auf "debug" schalten. Dann findest du es im normalen ioBroker Log. Bitte nicht da rauskopieren (Zeilen zu lang) sondern die Datei runterladen.

Ich hab dir mal der Einfachheitshalber einen Screenshot angehangen, ich hoffe das ist okay. 
Hab es auch noch mal beobachtet, der Ablauf ist folgendermaßen: 
Lampe einschalten: Lampe geht an, aber Schaltzustand direkt wieder auf false. 
Ich betätige noch mal den Button im HomeKit, danach zeigt mir HomeKit auch an das die Lampe an ist, wird aber beim zweiten mal betätigen nicht geschaltet. 

> Ja. https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#wait - gibts auch als Blockly-Block

Puh, ich glaub damit kann ich leider nichts anfangen. 

Mir wäre es am liebsten, wenn ich den Adapter generell darauf "programmieren" könnte das er Befehle grundsätzlich mit Zeit=x Versatz sendet. 

Hat auch den Hintergrund, dass ich in HomeKit Szenen programmiert habe. Zum Beispiel "Kino". Da werden mehre Steckdosen, Licht + Rollos gleichzeitig geschaltet. 
Hast du dafür eventuell eine Lösung parat? 
Vielen Dank schonmal vorab! 
<img width="1705" alt="Bildschirmfoto 2022-02-28 um 13 11 05" src="https://user-images.githubusercontent.com/100558141/155981952-a827655b-181a-4ee2-b680-943549b8cffa.png">

**Comment by Burny08** [comment]
Danke für deine Hilfe.
Ich habe mich jetzt vorerst für den leichtesten Weg entschieden: Ich nutze den Ikea Gateway direkt in HomeKit ohne Umweg über iOBroker (ist ja HomeKit fähig). Ist zwar etwas schade, aber für mich momentan der einfachste Weg.
Ich behalte deinen Adapter trotzdem drin, vielleicht hast du ja langfristig mal vor etwas in die Richtung zu optimieren :) 
Vielen Dank dennoch für deine Arbeit!
