### ISSUE TITLE
level.color.rgb is not RGB its HEX

### ISSUE THREAD

**Issue by Kev0123** [AlCalzone/ioBroker.tradfri#750]
Hi,

like the title says the colorspace is not given in RGB like 255,255,255 instead its #ffffff

or am I getting something wrong here?

Regards 
KEvin

**Comment by AlCalzone** [comment]
Not sure what you mean?

https://www.iobroker.net/#en/documentation/dev/stateroles.md

![grafik](https://user-images.githubusercontent.com/17641229/157092506-762969ad-0591-483a-8938-88e0a49cbea8.png)

🤷🏻‍♂️

**Comment by Kev0123** [comment]
There is no information difference between both but, as far as I understand RGB has to be in the format 255,255,255 and HEX will be #ffffff.
Its only a wording issue in this case. This one would be correct :
![image](https://user-images.githubusercontent.com/19821853/157093593-352056a8-b457-46f1-a9a9-60ef78c996c3.png)

Not a real bug but something which catched my eye as I synced WLED to tradfri

**Comment by AlCalzone** [comment]
I don't see a `level.color.hex` role definition in the documentation and tradfri's `level.color.rgb` state value matches the format specified there, so I'm inclined to say WLED does it incorrectly.
Also the HEX value is RGB, just in hexadecimal form. I don't think it makes sense to duplicate every value.

**Comment by Apollon77** [comment]
If

**Comment by AlCalzone** [comment]
I've confirmed with the other core developers. The `#rrggbb` form is the only correct one, there is no `level.color.hex` role.
If your screenshot above is from the WLED adapter, then this should really be an issue in the WLED adapter which doesn't conform with the defined roles.
