### ISSUE TITLE
The Adapter doesn't connect

### ISSUE THREAD

**Issue by millegal** [AlCalzone/iobroker.tradfri#8]
This is the Message in oibroker's log:

tradfri.0 | 2017-08-18 09:25:19.461 | error | unhandled promise rejection: No security parameters given for the resource at coaps://gw-*****************
-- | -- | -- | --

**Comment by AlCalzone** [comment]
When did you install the adapter? I changed the behaviour for connection by hostname a few days ago, it should have fixed the issue you mention.

**Comment by AlCalzone** [comment]
doesn't seem to be relevant... closing
