### ISSUE TITLE
Support for Ikea Dirigera

### ISSUE THREAD

**Issue by LarsTh3Lars** [AlCalzone/ioBroker.tradfri#841]
Hey there,
I wonder if it will be possible to support the new Ikea Dirigera gateway with this tradfri-Adapter?

**Comment by AlCalzone** [comment]
I haven't looked into that.

However I think that one will use the new Matter standard, so it will probably work with the matter adapters @Apollon77 is working on.

**Comment by Apollon77** [comment]
Yes, once the Metter firware is there and the adapters. In the meantime homekit-controller should also work because Dirigera supports Homekit

**Comment by LarsTh3Lars** [comment]
@AlCalzone @Apollon77 
Thank you - I wasn't aware that you are working on a Matter adapter.

**Comment by Apollon77** [comment]
maybe subscribe to https://github.com/ioBroker/AdapterRequests/issues/699 to get updates

**Comment by luxi-asphericon** [comment]
Hi,
I read here that the hub is not supported because at some point Matter could work at Ikea and alternatively Homekit is running.
For example, I run iobroker..... 8-0

**Comment by Apollon77** [comment]
The hub is also not supported because Dirigera is not comparable to Tradfri from what we know, so when it would be more an own adapter for Dirigera

**Comment by luxi-asphericon** [comment]
Oh, I wasn't aware that ikea created something completely new. 
Then I have to put up with the fact that I can't control my blinds from iobroker. 
Thanks for the work

**Comment by Apollon77** [comment]
As said: Homekit-Controller adapter connects to the Dirigera device already, Matter once adapter and FW is there most likely too

**Comment by Holger-Will** [comment]
maybe a bit off topic here, but how do you connect a dirigera with the homekit-controller? for me it does not show up in the list of pairable devices...

**Comment by Apollon77** [comment]
.. Yes very offtopic here, why not ask in forum or in homekir controller repo?

PLease make sure UDP/MDNS messages can flow betwen the ipbroker host and the dirigera without blocked yb anything (e.gdocker or whatever pot firewalls)
